# -------- Default Configuration -------- #

baseURL = 'https://job.yikzero.com'
languageCode = 'zh-CN'
title = 'yikZero'
theme = "roominess"
sectionPagesMenu = "main"

# -------- Default Parameters -------- #

[params]
    favicon = "img/favicon.ico"
    logo = "img/logo.svg"
    #Meta data
    description = "Show Myself"
    author = "yikZero"
    #noodleContent
    noodle_title = "å—¨<font class='noodle-point'>Â·</font>æˆ‘æ˜¯å¼ æ¯…å‰ã€‚<br/>ç•Œé¢äº¤äº’è®¾è®¡å¸ˆã€‚"
    noodle_desc = "ç›®å‰ï¼Œæˆ‘åœ¨æ­å· @äºšä¿¡ç§‘æŠ€ å·¥ä½œï¼Œ<br/>ä¸€å¹´ç•Œé¢äº¤äº’è®¾è®¡ç»éªŒã€‚<br/>æˆ‘å–œæ¬¢åšè®¾è®¡ã€å†™ä»£ç ã€ç ”ç©¶äº›æ–°å¥‡ç©æ„ ğŸ˜Šã€‚"
    noodle_email = "i@yikzero.com"
    #Copyright
    copyright = "Build with Hugo<br/>Copyright 2022 Â© yikZero"

    # -------- Social site -------- #
    [[params.social]]
    name = "E-Mail"
    link = "mailto:i@yikzero.com"

    [[params.social]]
    name = "Blog"
    link = "https://ro.yikzero.com"

    [[params.social]]
    name = "Github"
    link = "https://github.com/yikzero"

# -------- Menu -------- #

[menu]
    [[menu.main]]
    identifier = 'homepage'
    name = 'é¦–é¡µ'
    url = '/'
    weight = 1

    [[menu.main]]
    identifier = 'projects'
    name = 'é¡¹ç›®'
    url = '/projects/'
    weight = 2
    
    [[menu.main]]
    identifier = 'gallery'
    name = 'è®¾è®¡å±•è§ˆé¦†'
    url = '/gallery/'
    weight = 3

    [[menu.main]]
    identifier = 'about'
    name = 'å…³äºæˆ‘'
    url = '/about/'
    weight = 4

# -------- Plugins -------- #
# CSS Plugins
[[params.plugins.css]]
link = "css/font.css"

#JS Plugins
# [[params.plugins.js]]
# link = "plugins/waterfall.min.js"